require:
  - rubocop-performance
  - rubocop-rspec

inherit_gem:
  rentacop:
    - rentacop.yml
    - rspec.yml

AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - 'debug.rb'
    - 'dev/**/*'

# Allow @instance_variables in some legacy cases
RSpec/InstanceVariable:
  Exclude:
    - spec/active_cabinet/active_cabinet_metaclass_spec.rb

# Using the `all` matcher does not work here
RSpec/IteratedExpectation:
  Exclude:
    - spec/active_cabinet/active_cabinet_metaclass_spec.rb